name: CI
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

defaults:
  run:
    shell: bash -l {0}

jobs:
  unix:
    
    runs-on: ${{ matrix.os }}
     
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, macos-11, macos-12]

    steps:
      - uses: actions/checkout@v2

      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v1
      
      - name: install mamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: environment-dev.yml
          environment-name: xeus-nelson

      - name: cmake configure
        run: |
          mkdir -p build
          cd build
          cmake .. \
            -DCMAKE_PREFIX_PATH=$CONDA_PREFIX \
            -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX \
            -DCMAKE_INSTALL_LIBDIR=lib \
            -DCMAKE_C_COMPILER=$CC \
            -DCMAKE_CXX_COMPILER=$CXX

      - name: install
        run: |
          cd build
          make -j ${{ steps.cpu-cores.outputs.count }} install

      - name: test
        run: |
          cd test
          pytest .  --reruns 5

  win:
    
    runs-on: ${{ matrix.os }}
     
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, windows-2022]

    steps:
      - uses: actions/checkout@v2

      - name: install mamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: environment-dev.yml
          environment-name: xeus-nelson

      - name: micromamba shell hook
        shell: powershell
        run: |
          micromamba shell hook -s cmd.exe -p C:\Users\runneradmin\micromamba-root

      - name: cmake configure
        shell: cmd
        run: |
          call C:\Users\runneradmin\micromamba-root\condabin\micromamba.bat activate xeus-nelson
          mkdir -p build
          cd build
          cmake .. ^
            -GNinja ^
            -DCMAKE_BUILD_TYPE=Release ^
            -DCMAKE_INSTALL_PREFIX="%CONDA_PREFIX%\Library" 

      - name: build
        shell: cmd
        run: |
          call C:\Users\runneradmin\micromamba-root\condabin\micromamba.bat activate xeus-nelson
          cd build
          set CL=/MP
          ninja install

      - name: test
        shell: cmd
        run: |
          call C:\Users\runneradmin\micromamba-root\condabin\micromamba.bat activate xeus-nelson
          cd test
          pytest .  --reruns 5

  emscripten_wasm:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        emsdk_ver: ["3.1.45"]

    steps:
      - uses: actions/checkout@v2

      - name: Install mamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: environment-wasm-build.yml
          environment-name: xeus-nelson-wasm-build

      - name: Setup emsdk
        run: |
          micromamba activate xeus-nelson-wasm-build
          emsdk install ${{matrix.emsdk_ver}}     

      - name: Build xeus-nelson
        run: |
          micromamba activate xeus-nelson-wasm-build

          emsdk activate ${{matrix.emsdk_ver}}
          source $CONDA_EMSDK_DIR/emsdk_env.sh

          micromamba create -f environment-wasm-host.yml --platform=emscripten-wasm32
          
          mkdir build
          pushd build

          export EMPACK_PREFIX=$MAMBA_ROOT_PREFIX/envs/xeus-nelson-wasm-build
          export PREFIX=$MAMBA_ROOT_PREFIX/envs/xeus-nelson-wasm-host
          export CMAKE_PREFIX_PATH=$PREFIX
          export CMAKE_SYSTEM_PREFIX_PATH=$PREFIX

          emcmake cmake \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_FIND_ROOT_PATH_MODE_PACKAGE=ON \
            -DXEUS_NELSON_EMSCRIPTEN_WASM_BUILD=ON \
            ..

          make -j5
  
